apiVersion: v1
data:
  consensus: MTU3ZmYyMGM5NTMwYTBmNDc0MjU5NzEzNDk0YTZhMDQ0NjRmMTg2ZmRlMDQ4MmNkNWIyNDNiNjM0MzcyYjA4ZDdiZGEwZTQ2YjQ0OGFhNzlkZGRiMjBkYWVlODJjNGZjOTliZjRiZjkxZDZiNTNmNmZkYzM0YzFhYTFiMTM1YzM=
  consensus.pub: N2JkYTBlNDZiNDQ4YWE3OWRkZGIyMGRhZWU4MmM0ZmM5OWJmNGJmOTFkNmI1M2Y2ZmRjMzRjMWFhMWIxMzVjMw==
  service: ZmM0MjVhZDUxNzdmNmVkOWFiMTIzZjA1NzdmNmM5MTA5ZjRlOWE2NzE0M2I5ODQ0NjJlMTVlNzdhYzYzODY1YjM2MWNhNWEwYWI2OGJmZDk1ZWY1NDlhOTA2ZTY4MWM2ZTUxYzc2NWZlODhkMDRhMjAxNzFiMTE3N2I4ZGUwNzc=
  service.pub: MzYxY2E1YTBhYjY4YmZkOTVlZjU0OWE5MDZlNjgxYzZlNTFjNzY1ZmU4OGQwNGEyMDE3MWIxMTc3YjhkZTA3Nw==
kind: Secret
metadata:
  name: dmbc02-keys
  labels:
    app: dmbc02
type: Opaque