[package]
name = "dmarket-blockchain"
version = "0.1.0"
authors = ["Ilya Sinyakin <sinyakin.ilya@gmail.com>"]

[lib]
name = "dmbc"
path = "src/lib.rs"

[[bin]]
name = "dmarket-blockchain"
path = "src/main.rs"
test = false
bench = false
doc = false

[[bin]]
name = "fuzz"
path = "src/bin/fuzz.rs"
test = false
bench = false
doc = false

[[bin]]
name = "setup-fuzz"
path = "src/bin/setup_fuzz.rs"
test = false
bench = false
doc = false

[dependencies]
iron = "0.6.0"
params = "0.8.0"
bodyparser = "0.8.0"
router = "0.6.0"
nats = { git = "https://github.com/jedisct1/rust-nats", rev = "21919e5" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
toml = "0.4.5"
uuid = { version = "0.5", features = ["v5"] }
exonum = "0.4"
exonum-configuration = "0.4"
exonum-testkit = "0.1"
bincode = "*"

[dev-dependencies]
afl = "0.3"

