[package]
name = "dmarket-blockchain"
version = "0.1.0"
authors = ["Ilya Sinyakin <sinyakin.ilya@gmail.com>"]

[dependencies]
iron = "0.5.1"
bodyparser = "0.7.0"
router = "0.5.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
exonum = { git = "https://github.com/exonum/exonum.git" }
toml = "0.4.5"