[package]
name = "dmarket-blockchain"
version = "0.1.0"
authors = ["Ilya Sinyakin <sinyakin.ilya@gmail.com>"]

[lib]
name = "dmbc"
path = "src/lib.rs"

[[bin]]
name = "dmarket-blockchain"
path = "src/main.rs"
test = false
bench = false
doc = false

[dependencies]
iron = "0.5.1"
params = "*"
bodyparser = "0.7.0"
router = "0.5.1"
nats="*"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
toml = "0.4.5"
uuid = { version = "0.5", features = ["v5"] }
exonum = "0.3"
exonum-configuration = "0.3"
