apiVersion: apps/v1
kind: Deployment
metadata:
  name: dmbc05
  labels:
    app: dmbc05
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-nodepool
                    operator: In
                    values:
                      - dmbc-pool-prod-01
