[api]
current_node = "node0"
address = "127.0.0.1:8000"
private_address = "127.0.0.1:8001"
peer_address = "0.0.0.0:2000"
peers = []
keys_path = "./var/keys"

[db]
path = "./var/db"

[nats]
enabled = true
addresses = ["nats://vRJY4vOIoNSsG72F:UCF0IsKwMlYON4g7@35.197.200.238:4222"]
queuename = "transaction.commit"

[service_discovery]
address = "127.0.0.1:3000/nodes"
