[api]
current_node = "node0"
address = "0.0.0.0:8000"
private_address = "0.0.0.0:8001"
peer_address = "0.0.0.0:2000"
peers = []
keys_path = "./var/keys"

[db]
path = "./var/db"

[nats]
addresses = ["nats://vRJY4vOIoNSsG72F:UCF0IsKwMlYON4g7@35.197.200.238:4222"]
queuename = "transaction.commit"
