[api]
current_node = "node0"
address = "127.0.0.1:8000"
private_address = "127.0.0.1:8001"
peer_address = "127.0.0.1:2000"
peers = []
keys_path = "./var/keys"
is_validator = true

[db]
path = "./var/db"

[nats]
enabled = true
addresses = ["nats://127.0.0.1:4222"]
queuename = "transaction.commit"

[service_discovery]
address = "127.0.0.1:3000/nodes"
