---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dmbc05
  labels:
    app: dmbc05
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1100Gi
  storageClassName: standard