[package]
name = "dmbc-bot"
version = "0.1.0"
authors = ["Mikola Samardak <niksaak@gmail.com>"]

[dependencies]
dmbc = { path = "../dmbc" }
rand = "0.4.2"
exonum = "0.4"
serde = "1.0.30"
serde_json = "1.0"
nix = "*"
curl = "0.4.11"
log = "*"
env_logger = "*"